//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelShare.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotelShare.Web.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить жанры.
        /// </summary>
        public static string AddGenres {
            get {
                return ResourceManager.GetString("AddGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить платформы.
        /// </summary>
        public static string AddPlatforms {
            get {
                return ResourceManager.GetString("AddPlatforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить в корзину.
        /// </summary>
        public static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Награды.
        /// </summary>
        public static string Awards {
            get {
                return ResourceManager.GetString("Awards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуться назад.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забанить.
        /// </summary>
        public static string Ban {
            get {
                return ResourceManager.GetString("Ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Банк.
        /// </summary>
        public static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата через банк.
        /// </summary>
        public static string BankPayment {
            get {
                return ResourceManager.GetString("BankPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корзина.
        /// </summary>
        public static string Basket {
            get {
                return ResourceManager.GetString("Basket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить издателя.
        /// </summary>
        public static string ChangeRoom {
            get {
                return ResourceManager.GetString("ChangeRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оформить.
        /// </summary>
        public static string Checkout {
            get {
                return ResourceManager.GetString("Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коментарий.
        /// </summary>
        public static string CommentGame {
            get {
                return ResourceManager.GetString("CommentGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарии.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментариев.
        /// </summary>
        public static string CommentsGame {
            get {
                return ResourceManager.GetString("CommentsGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О компании.
        /// </summary>
        public static string CompanyInformation {
            get {
                return ResourceManager.GetString("CompanyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название компании.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверидть пароль.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакты.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать новую игру.
        /// </summary>
        public static string CreateGame {
            get {
                return ResourceManager.GetString("CreateGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить жанры.
        /// </summary>
        public static string DeleteGenres {
            get {
                return ResourceManager.GetString("DeleteGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить платформы.
        /// </summary>
        public static string DeletePlatforms {
            get {
                return ResourceManager.GetString("DeletePlatforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детали.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Больше не издается.
        /// </summary>
        public static string Discontinued {
            get {
                return ResourceManager.GetString("Discontinued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скидка.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скачать.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почта.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простое решение для повседневных задач.
        /// </summary>
        public static string EmpoweredSolutionswithSimpleProcess {
            get {
                return ResourceManager.GetString("EmpoweredSolutionswithSimpleProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корзина пустая.
        /// </summary>
        public static string EmptyBasket {
            get {
                return ResourceManager.GetString("EmptyBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Английский.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер файла.
        /// </summary>
        public static string File_size {
            get {
                return ResourceManager.GetString("File size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтровать.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следите за нами.
        /// </summary>
        public static string FollowUs {
            get {
                return ResourceManager.GetString("FollowUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to От.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Из блога.
        /// </summary>
        public static string From_the_Blog {
            get {
                return ResourceManager.GetString("From the Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общее количество игр.
        /// </summary>
        public static string GameCount {
            get {
                return ResourceManager.GetString("GameCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание игры.
        /// </summary>
        public static string GameDescription {
            get {
                return ResourceManager.GetString("GameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жанры.
        /// </summary>
        public static string Genres {
            get {
                return ResourceManager.GetString("Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Связь с нами.
        /// </summary>
        public static string GetInTouch {
            get {
                return ResourceManager.GetString("GetInTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуться к списку игр.
        /// </summary>
        public static string GoBacktoGameList {
            get {
                return ResourceManager.GetString("GoBacktoGameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Домашняя страница.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игра.
        /// </summary>
        public static string Hotel {
            get {
                return ResourceManager.GetString("Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отели.
        /// </summary>
        public static string Hotels {
            get {
                return ResourceManager.GetString("Hotels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата через IBox.
        /// </summary>
        public static string IBoxPayment {
            get {
                return ResourceManager.GetString("IBoxPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Едениц.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество едениц.
        /// </summary>
        public static string ItemsPerPage {
            get {
                return ResourceManager.GetString("ItemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключ.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Узнай больше.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недостаточно прав для доступа к ресурсу.
        /// </summary>
        public static string LoginDenied {
            get {
                return ResourceManager.GetString("LoginDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказать.
        /// </summary>
        public static string MakeOrder {
            get {
                return ResourceManager.GetString("MakeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление заказами.
        /// </summary>
        public static string ManageOrders {
            get {
                return ResourceManager.GetString("ManageOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление ролями.
        /// </summary>
        public static string ManageRoles {
            get {
                return ResourceManager.GetString("ManageRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление пользователями.
        /// </summary>
        public static string ManageUsers {
            get {
                return ResourceManager.GetString("ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить комментарий.
        /// </summary>
        public static string NewComment {
            get {
                return ResourceManager.GetString("NewComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Итог заказа.
        /// </summary>
        public static string OderSummary {
            get {
                return ResourceManager.GetString("OderSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказ.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История заказов.
        /// </summary>
        public static string OrderHistory {
            get {
                return ResourceManager.GetString("OrderHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другой.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поджанр.
        /// </summary>
        public static string ParentGenre {
            get {
                return ResourceManager.GetString("ParentGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата.
        /// </summary>
        public static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Платформы.
        /// </summary>
        public static string Platforms {
            get {
                return ResourceManager.GetString("Platforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Платформы.
        /// </summary>
        public static string Playableon {
            get {
                return ResourceManager.GetString("Playableon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Диапазон цен.
        /// </summary>
        public static string PriceRange {
            get {
                return ResourceManager.GetString("PriceRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Публиковать.
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цитировать.
        /// </summary>
        public static string Quote {
            get {
                return ResourceManager.GetString("Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обработать результаты.
        /// </summary>
        public static string RefineResults {
            get {
                return ResourceManager.GetString("RefineResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выпущено.
        /// </summary>
        public static string Released {
            get {
                return ResourceManager.GetString("Released", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата релиза.
        /// </summary>
        public static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ответить.
        /// </summary>
        public static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отзывы.
        /// </summary>
        public static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роль.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Издатель.
        /// </summary>
        public static string Room {
            get {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Издатели.
        /// </summary>
        public static string Rooms {
            get {
                return ResourceManager.GetString("Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        public static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найти игру.
        /// </summary>
        public static string SearchGame {
            get {
                return ResourceManager.GetString("SearchGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылки сайта.
        /// </summary>
        public static string SiteLinks {
            get {
                return ResourceManager.GetString("SiteLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Социальные сети.
        /// </summary>
        public static string SocialMedia {
            get {
                return ResourceManager.GetString("SocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортировка.
        /// </summary>
        public static string Sorting {
            get {
                return ResourceManager.GetString("Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промежуточная цена.
        /// </summary>
        public static string Subtotal {
            get {
                return ResourceManager.GetString("Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налоги.
        /// </summary>
        public static string Taxes {
            get {
                return ResourceManager.GetString("Taxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рекомендации.
        /// </summary>
        public static string Testimonials {
            get {
                return ResourceManager.GetString("Testimonials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to До.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всего.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновления Twitter.
        /// </summary>
        public static string TwitterUpdates {
            get {
                return ResourceManager.GetString("TwitterUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В наявности.
        /// </summary>
        public static string UnitsInStock {
            get {
                return ResourceManager.GetString("UnitsInStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестный.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата через Visa.
        /// </summary>
        public static string VisaPayment {
            get {
                return ResourceManager.GetString("VisaPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посетить наш блог.
        /// </summary>
        public static string VisitBlog {
            get {
                return ResourceManager.GetString("VisitBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сделай свою жизнь проще!.
        /// </summary>
        public static string WhatCanMakeYourLifeEasier {
            get {
                return ResourceManager.GetString("WhatCanMakeYourLifeEasier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что вы получаете.
        /// </summary>
        public static string WhatYouGet {
            get {
                return ResourceManager.GetString("WhatYouGet", resourceCulture);
            }
        }
    }
}
